name: ci

on:
  workflow_call:
  push:
    branches: [ "feature/*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore
    
      - name: Build app
        run: dotnet build --configuration Release --no-restore
      
      - name: Publish Linux app for tests
        run: dotnet publish src/Panbyte.App/Panbyte.App.csproj -c Release --sc true -r linux-x64 /p:PublishSingleFile=true /p:UseAppHost=true /p:DebugType=None /p:DebugSymbols=false -p:PublishDir=out

      - name: Tests
        run: dotnet test
        env:
          ACTIONS_APP_PATH: ${{ github.workspace }}/src/Panbyte.App/out/panbyte
